package com.rxvlvxr.models;

import jakarta.persistence.*;

import java.time.LocalDateTime;

// класс сущности measurement
@Entity
@Table(name = "measurement")
public class Measurement {
    // поясняем что это id
    @Id
    // соответсвует GENERATED BY DEFAULT AS IDENTITY
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;
    @Column(name = "value")
    private Double value;
    @Column(name = "raining")
    private Boolean raining;
    // указываем на связь (связанные таблицы подгружаться автоматические не будут, т.к. LAZY)
    @ManyToOne(fetch = FetchType.LAZY)
    // указываем на внешний ключ
    @JoinColumn(name = "sensor", referencedColumnName = "name")
    private Sensor sensor;
    @Column(name = "measured_at")
    @Temporal(TemporalType.TIMESTAMP)
    private LocalDateTime measuredAt;

    public Measurement() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Double getValue() {
        return value;
    }

    public void setValue(Double value) {
        this.value = value;
    }

    public Boolean getRaining() {
        return raining;
    }

    public void setRaining(Boolean raining) {
        this.raining = raining;
    }

    public Sensor getSensor() {
        return sensor;
    }

    public void setSensor(Sensor sensor) {
        this.sensor = sensor;
    }

    public LocalDateTime getMeasuredAt() {
        return measuredAt;
    }

    public void setMeasuredAt(LocalDateTime measuredAt) {
        this.measuredAt = measuredAt;
    }
}
